import "../globals.css";
import Navbar from '../components/Navbar.js';
import Sidebar from '../components/Sidebar.js';
import Settings from '../components/Settings.js';
import NewJob from '../components/NewJob/NewJob.js';
import { SettingsProvider } from "../context/SettingsContext";
import { fontSans } from "../fonts.js";
import { LocationProvider } from "../context/LocationContext";
import { StatusProvider } from "../context/StatusContext";
import { NewJobProvider } from "../context/NewJobContext"



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <>
        <Navbar/>
          <Sidebar/>
          <main style={{marginLeft:'240px',marginTop:'50px'}}>
            {children}
          </main>



    <Settings />
    <NewJob/>
    </>
  );
}
